# Generated by Django 3.2.9 on 2022-02-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_of_recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipecomments',
            options={'verbose_name': 'Комментарий к рецепту', 'verbose_name_plural': 'Комментарии к рецепту'},
        ),
    ]
