# Generated by Django 3.2.9 on 2022-02-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_of_recipes', '0003_alter_ingredient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit_of_measurement',
            field=models.CharField(choices=[('KG', 'кг'), ('G', 'г'), ('L', 'л'), ('ML', 'мл'), ('PIECE', 'шт.'), ('TEASPOON', 'ч.л.'), ('EMPTY', '')], max_length=10, verbose_name='Единица измерения'),
        ),
    ]
