# Generated by Django 3.2.9 on 2022-02-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_of_recipes', '0005_alter_ingredient_unit_of_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit_of_measurement',
            field=models.CharField(blank=True, choices=[('kg', 'кг'), ('g', 'г'), ('l', 'л'), ('ml', 'мл'), ('piece', 'шт.'), ('teaspoon', 'ч.л.')], max_length=10, null=True, verbose_name='Единица измерения'),
        ),
    ]
