# Generated by Django 3.2.9 on 2022-02-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_of_recipes', '0006_auto_20220217_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit_of_measurement',
            field=models.CharField(blank=True, choices=[('кг', 'кг'), ('г', 'г'), ('л', 'л'), ('мл', 'мл'), ('шт.', 'шт.'), ('ч.л.', 'ч.л.')], max_length=10, null=True, verbose_name='Единица измерения'),
        ),
    ]
